### ISSUE TITLE
2023 ghosts exposure?

### ISSUE THREAD

**Issue by OpusMortalis** [YimMenu-Lua/RandomEvents#10]
At some points, if i select an event from ghosts exposure and teleport to it, im teleported to sandy shores for the location of the ghost of Johnny, but i tried to mess with the ingame time but never got able to get the 2023 ghosts.

If i mess with the time, im teleported to the ghosts in LS. I tried to enable and disable Bypass Requirments to see if it helps, but it doesnt. 

Is there a way to have 2023 ghosts?

**Comment by ShinyWasabi** [comment]
Is the "Enable Tunables" checkbox toggled? If so, you need to untoggle it as it will invalidate the 2023 ghosts.

Go to Settings -> Debug -> Tunables. Type in `ENABLE_HALLOWEEN_GHOSTHUNT` in the Tunable box. Set the value to 1.

**Comment by ApexScorpio** [comment]
Works well, thanks. 

Its a just a shame i cant make it active for other players in the session. It works only for me
