### ISSUE TITLE
is there an event listed to trigger "police rescue - patrick mcreary"?

### ISSUE THREAD

**Issue by lonelybud** [YimMenu-Lua/RandomEvents#11]
it seems to be a random event and is also mentioned in website here https://gtaweb.eu/gtao-map/ls/-/police-rescue-patrick-mcreary/sm=2

**Comment by ShinyWasabi** [comment]
https://github.com/YimMenu-Lua/RandomEvents/issues/8

**Comment by lonelybud** [comment]
my bad i did nt searched it. thank you dear!
