### ISSUE TITLE
(IDEA) Spawn on Player

### ISSUE THREAD

**Issue by bigdaddy2142** [YimMenu-Lua/RandomEvents#4]
Could you have a drop down menu to spawn the event on a certain player? Such as Phantom Car or Gooch?

**Comment by ShinyWasabi** [comment]
@bigdaddy2142 Is this what you mean? https://imgur.com/a/SUCoCmp
It includes Slashers & Gooch as well.

**Comment by bigdaddy2142** [comment]
> @bigdaddy2142 Is this what you mean? https://imgur.com/a/SUCoCmp It includes Slashers & Gooch as well.

That's exactly what I meant dude awesome! ❤️
