### ISSUE TITLE
Error when Loading the Script

### ISSUE THREAD

**Issue by minebloxhd** [YimMenu-Lua/RandomEvents#6]
When I try to load the Script, the Menu does not show up in the GUI and it says "Warning: Tunable is not Active"

**Comment by ShinyWasabi** [comment]
That's not an error. That just means the tunable to activate the event is not enabled. You can find the Random Events tab in the Network section. To enable the tunables, tick the "Enable Tunables" checkbox in the settings collapsing header.
![1](https://github.com/user-attachments/assets/da4cb379-9d15-4d71-a156-abf48cdec1ea)

**Comment by ShinyWasabi** [comment]
Closing this now as it's an invalid issue.
