### ISSUE TITLE
LUA Script not registered. 

### ISSUE THREAD

**Issue by XPCOLLECTOR** [YimMenu-Lua/RandomEvents#7]
When Trying to launch Ramdom_events .lua, the following error message occurs: 
[19:42:54.0896685][FATAL/lua_manager.cpp:397] random_events.lua: ...\gurpr\AppData\Roaming\YimMenu\scripts\random_events.lua:280: attempt to call a nil value (field 'is_active')
stack traceback:
        ...\gurpr\AppData\Roaming\YimMenu\scripts\random_events.lua:280: in upvalue 'REGISTER_MAX_VARIATIONS'
        ...\gurpr\AppData\Roaming\YimMenu\scripts\random_events.lua:640: in function <...\gurpr\AppData\Roaming\YimMenu\scripts\random_events.lua:638>

**Comment by ShinyWasabi** [comment]
You are probably using an old version of YimMenu. Download the latest release.

**Comment by DigitalDonutt** [comment]
I am also having this issue, I downloaded today and its not functioning.

**Comment by ShinyWasabi** [comment]
Can you send me your complete log file?

**Comment by DigitalDonutt** [comment]
[16:22:29.5836146]16:22:29.5836047][31m[FATAL/lua_manager.cppFATAL/lua_module.cpp:80:397] random_events.lua: ...\user\AppData\Roaming\YimMenu\scripts\random_events.lua:283: attempt to index a nil value (global 'scr_function')
stack traceback:
        ...\user\AppData\Roaming\YimMenu\scripts\random_events.lua:283: in upvalue 'REGISTER_MAX_VARIATIONS'
        ...\user\AppData\Roaming\YimMenu\scripts\random_events.lua:640: in function <...\user\AppData\Roaming\YimMenu\scripts\random_events.lua:638>
] ...\user\AppData\Roaming\YimMenu\scripts\random_events.lua:283: attempt to index a nil value (global 'scr_function')
stack traceback:
        ...\user\AppData\Roaming\YimMenu\scripts\random_events.lua:283: in upvalue 'REGISTER_MAX_VARIATIONS'
        ...\user\AppData\Roaming\YimMenu\scripts\random_events.lua:640: in function <...\user\AppData\Roaming\YimMenu\scripts\random_events.lua:638>

**Comment by DigitalDonutt** [comment]
[16:22:16.7114693][FATAL/lua_module.cpp:80] ...\user\AppData\Roaming\YimMenu\scripts\random_events.lua:710: attempt to concatenate a nil value (field '?')
stack traceback:
        ...\user\AppData\Roaming\YimMenu\scripts\random_events.lua:710: in function <...\user\AppData\Roaming\YimMenu\scripts\random_events.lua:677>

**Comment by ShinyWasabi** [comment]
I told you to send me your full log file... It's the cout.log file in the YimMenu appdata folder.
Also, from what I see in the error message, you are definitely using an old version of YimMenu. We added the `scr_function` class 2 weeks ago.

**Comment by DigitalDonutt** [comment]
I will warn you it is quite long, I have tried only enabling it by its self and with other scripts. I downloaded it yesterday and I don't know what happened but the script is throwing errors, Thousands of errors as you will see from the log.

[cout.log](https://github.com/user-attachments/files/16697354/cout.log)

**Comment by ShinyWasabi** [comment]
Well, look at this date dummy:
```
	Branch:	master
	Hash:	b92a41bd8438026a591b4efdedf9ac4597278f76
	Date:	Fri Aug 2 10:09:26 2024
```
You are using a YimMenu version almost 1 month old. This makes your issue invalid.
Download the latest one from here: https://github.com/YimMenu/YimMenu/releases/tag/nightly

**Comment by DigitalDonutt** [comment]
I was wrong, Thank you for assisting. I am a very new  to the world of having a menu. I appreciate it.
