### ISSUE TITLE
Can we have Patrick McReary random event ?

### ISSUE THREAD

**Issue by MDAtikurRahman181-15-2024** [YimMenu-Lua/RandomEvents#8]
This event does not appear now at all.

**Comment by ShinyWasabi** [comment]
It's not a "Random Event" code-wise, so I won't be adding it to this script.

**Comment by OpusMortalis** [comment]
Is there any other script where we can spawn the Patrick event, tho?

**Comment by ShinyWasabi** [comment]
I will make a script for it when I have the time.

**Comment by OpusMortalis** [comment]
amazing thanks

**Comment by ShinyWasabi** [comment]
https://github.com/YimMenu-Lua/PatrickMcReary
