### ISSUE TITLE
Is it possible to spawn events to other players?

### ISSUE THREAD

**Issue by OpusMortalis** [YimMenu-Lua/RandomEvents#9]
I know its possible to spawn the phantom car and the grootch to others players, but i would like to know if there is a way to add the possibility to spawn other events on the player, like the slasher, the cerebrus and the possessed animals

**Comment by ShinyWasabi** [comment]
Just launch the event as freemode host and have your friend trigger it.

**Comment by OpusMortalis** [comment]
i did it, but it didnt triggered for the other account. I even put the 2 accounts on the same spot, tho the other can see the slasher and the animal, but the event its not for him. The effects  like the drivers fire or the blood smoke dont show up for the other account, they target just my hacker account, and even with the cerebrus, the other account isnt even able to enter the car to deliver it, because the event spawned only for my hacking account.

**Comment by ShinyWasabi** [comment]
The commit https://github.com/YimMenu-Lua/RandomEvents/commit/8f5fa9c0ee24299692a0416626a8683aeac7a66d should resolve your issue.

**Comment by OpusMortalis** [comment]
Hello, thank you for your efford. In fact some events are already working, like cerebrus. 
unfortunatelly other events still dont trigger on other accounts like slashers possesed animals or Ghost exposure. They allow others to see the ghost/slasher/animal, but thats it. Taking a photo or interact with them does nothing. Only works the account that triggered the event. 

Regarding the patrick event, seems to be working good for the triggering account. Was that suposse to trigger for other players aswell? For me it only works for the account that has the menu

**Comment by ShinyWasabi** [comment]
@OpusMortalis I just tested all the random events with a friend, and he was able to trigger them all. It's just that some random events don't take a second participant, so your friend must trigger them first to become the host.

> Regarding the patrick event, seems to be working good for the triggering account. Was that suposse to trigger for other players aswell? For me it only works for the account that has the menu

It should work if they join your CEO/MC.

**Comment by OpusMortalis** [comment]
When I launch the event, it triggers automatically on my host account, instantaneously.

Can you give me some tip so I can prevent my hosing account to trigger it and allow the other account to have it?
